import type { Metadata } from "next";
import { Lora } from 'next/font/google';
import "../styles/globals.scss";

export const metadata: Metadata = {
  title: "Підтримуй",
  description: "Generated by create next app",
};

const lora = Lora({

});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lora.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
